///|
pub let dot_attr_boundingbox = "bb"

///|
pub let dot_attr_comment = "comment"

///|
pub let dot_attr_compound = "compound"

///|
pub let dot_attr_concentrate = "concentrate"

///|
pub let dot_attr_crossmin_limit = "mclimit"

///|
pub let dot_attr_damping = "Damping"

///|
pub let dot_attr_edgedir = "dir"

///|
pub let dot_attr_edgelen = "len"

///|
pub let dot_attr_epsilon = "epsilon"

///|
pub let dot_attr_fixedsize = "fixedsize"

///|
pub let dot_attr_fontname = "fontname"

///|
pub let dot_attr_fontsize = "fontsize"

///|
pub let dot_attr_headlabel = "headlabel"

///|
pub let dot_attr_headlp = "head_lp"

///|
pub let dot_attr_height = "height"

///|
pub let dot_attr_label = "label"

///|
pub let dot_attr_labelangle = "labelangle"

///|
pub let dot_attr_labeldistance = "labeldistance"

///|
pub let dot_attr_labelpos = "lp"

///|
pub let dot_attr_layout = "layout"

///|
pub let dot_attr_lhead = "lhead"

///|
pub let dot_attr_ltail = "ltail"

///|
pub let dot_attr_overlap = "overlap"

///|
pub let dot_attr_pack = "pack"

///|
pub let dot_attr_pad = "pad"

///|
pub let dot_attr_pos = "pos"

///|
pub let dot_attr_margin = "margin"

///|
pub let dot_attr_maxiter = "maxiter"

///|
pub let dot_attr_mindist = "mindist"

///|
pub let dot_attr_neato_model = "model"

///|
pub let dot_attr_nodesep = "nodesep"

///|
pub let dot_attr_simplex_limit = "nslimit"

///|
pub let dot_attr_rankdir = "rankdir"

///|
pub let dot_attr_ranksep = "ranksep"

///|
pub let dot_attr_ratio = "ratio"

///|
pub let dot_attr_sep = "sep"

///|
pub let dot_attr_shape = "shape"

///|
pub let dot_attr_splines = "splines"

///|
pub let dot_attr_spring_constant = "K"

///|
pub let dot_attr_start = "start"

///|
pub let dot_attr_style = "style"

///|
pub let dot_attr_taillabel = "taillabel"

///|
pub let dot_attr_taillp = "tail_lp"

///|
pub let dot_attr_weight = "weight"

///|
pub let dot_attr_width = "width"
