///|
pub let core_meta_antlr_token_file_path : String = "org/eclipse/elk/core/meta/parser/antlr/internal/InternalMetaData.tokens"

///|
pub let core_meta_antlr_token_file_content : String = "'!'=75\n" +
  "'!='=61\n" +
  "'!=='=63\n" +
  "'#'=42\n" +
  "'%'=74\n" +
  "'%='=55\n" +
  "'&&'=60\n" +
  "'&'=112\n" +
  "'('=41\n" +
  "')'=43\n" +
  "'*'=72\n" +
  "'**'=73\n" +
  "'*='=53\n" +
  "'+'=71\n" +
  "'++'=77\n" +
  "'+='=51\n" +
  "','=36\n" +
  "'-'=50\n" +
  "'--'=78\n" +
  "'-='=52\n" +
  "'->'=65\n" +
  "'.'=79\n" +
  "'..'=67\n" +
  "'..<'=66\n" +
  "'/'=49\n" +
  "'/='=54\n" +
  "':'=29\n" +
  "'::'=80\n" +
  "';'=85\n" +
  "'<'=56\n" +
  "'<>'=69\n" +
  "'='=32\n" +
  "'=='=39\n" +
  "'==='=62\n" +
  "'=>'=68\n" +
  "'>'=57\n" +
  "'>='=58\n" +
  "'?'=111\n" +
  "'?.'=81\n" +
  "'?:'=70\n" +
  "'['=82\n" +
  "']'=83\n" +
  "'advanced'=24\n" +
  "'algorithm'=40\n" +
  "'as'=76\n" +
  "'bundle'=14\n" +
  "'case'=89\n" +
  "'catch'=110\n" +
  "'category'=44\n" +
  "'clusters'=123\n" +
  "'compound'=122\n" +
  "'default'=31\n" +
  "'deprecated'=23\n" +
  "'description'=30\n" +
  "'disconnected'=124\n" +
  "'do'=92\n" +
  "'documentation'=22\n" +
  "'documentationFolder'=18\n" +
  "'edge_labels'=121\n" +
  "'edges'=115\n" +
  "'else'=87\n" +
  "'extends'=95\n" +
  "'extension'=98\n" +
  "'false'=101\n" +
  "'features'=46\n" +
  "'finally'=108\n" +
  "'for'=90\n" +
  "'global'=27\n" +
  "'group'=21\n" +
  "'idPrefix'=19\n" +
  "'if'=86\n" +
  "'import'=97\n" +
  "'inside_self_loops'=119\n" +
  "'instanceof'=64\n" +
  "'label'=16\n" +
  "'labels'=117\n" +
  "'legacyIds'=37\n" +
  "'lowerBound'=33\n" +
  "'metadataClass'=17\n" +
  "'multi_edges'=120\n" +
  "'new'=100\n" +
  "'nodes'=114\n" +
  "'null'=103\n" +
  "'option'=28\n" +
  "'output'=26\n" +
  "'package'=13\n" +
  "'parents'=113\n" +
  "'ports'=116\n" +
  "'preview'=45\n" +
  "'programmatic'=25\n" +
  "'requires'=38\n" +
  "'return'=106\n" +
  "'self_loops'=118\n" +
  "'static'=96\n" +
  "'super'=99\n" +
  "'supports'=48\n" +
  "'switch'=88\n" +
  "'synchronized'=109\n" +
  "'targets'=35\n" +
  "'throw'=105\n" +
  "'true'=102\n" +
  "'try'=107\n" +
  "'typeof'=104\n" +
  "'upperBound'=34\n" +
  "'val'=94\n" +
  "'validator'=47\n" +
  "'var'=93\n" +
  "'while'=91\n" +
  "'{'=15\n" +
  "'|'=84\n" +
  "'||'=59\n" +
  "'}'=20\n" +
  "RULE_ANY_OTHER=12\n" +
  "RULE_DECIMAL=8\n" +
  "RULE_HEX=6\n" +
  "RULE_ID=5\n" +
  "RULE_INT=7\n" +
  "RULE_ML_COMMENT=9\n" +
  "RULE_SL_COMMENT=10\n" +
  "RULE_STRING=4\n" +
  "RULE_WS=11\n" +
  "T__100=100\n" +
  "T__101=101\n" +
  "T__102=102\n" +
  "T__103=103\n" +
  "T__104=104\n" +
  "T__105=105\n" +
  "T__106=106\n" +
  "T__107=107\n" +
  "T__108=108\n" +
  "T__109=109\n" +
  "T__110=110\n" +
  "T__111=111\n" +
  "T__112=112\n" +
  "T__113=113\n" +
  "T__114=114\n" +
  "T__115=115\n" +
  "T__116=116\n" +
  "T__117=117\n" +
  "T__118=118\n" +
  "T__119=119\n" +
  "T__120=120\n" +
  "T__121=121\n" +
  "T__122=122\n" +
  "T__123=123\n" +
  "T__124=124\n" +
  "T__13=13\n" +
  "T__14=14\n" +
  "T__15=15\n" +
  "T__16=16\n" +
  "T__17=17\n" +
  "T__18=18\n" +
  "T__19=19\n" +
  "T__20=20\n" +
  "T__21=21\n" +
  "T__22=22\n" +
  "T__23=23\n" +
  "T__24=24\n" +
  "T__25=25\n" +
  "T__26=26\n" +
  "T__27=27\n" +
  "T__28=28\n" +
  "T__29=29\n" +
  "T__30=30\n" +
  "T__31=31\n" +
  "T__32=32\n" +
  "T__33=33\n" +
  "T__34=34\n" +
  "T__35=35\n" +
  "T__36=36\n" +
  "T__37=37\n" +
  "T__38=38\n" +
  "T__39=39\n" +
  "T__40=40\n" +
  "T__41=41\n" +
  "T__42=42\n" +
  "T__43=43\n" +
  "T__44=44\n" +
  "T__45=45\n" +
  "T__46=46\n" +
  "T__47=47\n" +
  "T__48=48\n" +
  "T__49=49\n" +
  "T__50=50\n" +
  "T__51=51\n" +
  "T__52=52\n" +
  "T__53=53\n" +
  "T__54=54\n" +
  "T__55=55\n" +
  "T__56=56\n" +
  "T__57=57\n" +
  "T__58=58\n" +
  "T__59=59\n" +
  "T__60=60\n" +
  "T__61=61\n" +
  "T__62=62\n" +
  "T__63=63\n" +
  "T__64=64\n" +
  "T__65=65\n" +
  "T__66=66\n" +
  "T__67=67\n" +
  "T__68=68\n" +
  "T__69=69\n" +
  "T__70=70\n" +
  "T__71=71\n" +
  "T__72=72\n" +
  "T__73=73\n" +
  "T__74=74\n" +
  "T__75=75\n" +
  "T__76=76\n" +
  "T__77=77\n" +
  "T__78=78\n" +
  "T__79=79\n" +
  "T__80=80\n" +
  "T__81=81\n" +
  "T__82=82\n" +
  "T__83=83\n" +
  "T__84=84\n" +
  "T__85=85\n" +
  "T__86=86\n" +
  "T__87=87\n" +
  "T__88=88\n" +
  "T__89=89\n" +
  "T__90=90\n" +
  "T__91=91\n" +
  "T__92=92\n" +
  "T__93=93\n" +
  "T__94=94\n" +
  "T__95=95\n" +
  "T__96=96\n" +
  "T__97=97\n" +
  "T__98=98\n" +
  "T__99=99\n"

///|
pub(all) struct MetaDataAntlrTokenFileProvider {
  marker : Unit
}

///|
pub fn new_meta_data_antlr_token_file_provider() -> MetaDataAntlrTokenFileProvider {
  { marker: () }
}

///|
pub fn MetaDataAntlrTokenFileProvider::get_antlr_token_file_path(
  self : MetaDataAntlrTokenFileProvider,
) -> String {
  ignore(self)
  core_meta_antlr_token_file_path
}

///|
pub fn MetaDataAntlrTokenFileProvider::get_antlr_token_file(
  self : MetaDataAntlrTokenFileProvider,
) -> String {
  ignore(self)
  core_meta_antlr_token_file_content
}
